services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=123456
    ports:
        - "3306:3306"
    volumes:
        - /root/docker/mysql:/etc/mysql/conf.d
        - /root/docker/data/:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:5.0
    ports:
        - "6379:6379"

  mq:
    container_name: mq 
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "1883:1883"
      - "5672:5672"
      - "61613:61613"
      - "61614:61614"
      - "8161:8161"
  zk:
    container_name: zk 
    image: zookeeper:3.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
